In [27]:
import os
import pandas as pd
from matplotlib import pyplot as plt
import datetime as dt
import pymongo
import math
os.chdir(r'C:\Users\bjros\OneDrive\Desktop\KU_Data_Analytics_Boot_Camp\Projects\Project_2\citi-service')

In [37]:
#GET DATA
citi_df = pd.read_csv("Resources/311_Call_Center_Service_Requests.csv")
citi_df_mod = citi_df[['SOURCE','DEPARTMENT','CATEGORY', 'TYPE', 'DETAIL', 'CREATION YEAR','CREATION DATE','CREATION TIME','STATUS','DAYS TO CLOSE','STREET ADDRESS','COUNCIL DISTRICT','LATITUDE', 'LONGITUDE']]

#CLEAN DATA
# 1) Rename Columns
citi_df_mod.columns = ['source', 'department', 'category', 'type', 'detail', 'creation_year', 'creation_date', 'creation_time', 'status', 'days_to_close', 'street_address', 'council_district','lat','lon']

# 2) Fill in NaN
citi_df_mod = citi_df_mod.fillna("unknown")

# 3) Filter by Source
citi_df_mod = citi_df_mod.loc[(citi_df_mod["source"] == "WEB") | (citi_df_mod["source"] == "PHONE") |(citi_df_mod["source"] == "EMAIL") |(citi_df_mod["source"] == "WALK") | (citi_df_mod["source"] == "MAIL") ]

# 4) Rename values in source column
citi_df_mod["source"] = citi_df_mod["source"].str.replace("WEB","Online")
citi_df_mod["source"] = citi_df_mod["source"].str.replace("PHONE","Phone")
citi_df_mod["source"] = citi_df_mod["source"].str.replace("EMAIL","Email")
citi_df_mod["source"] = citi_df_mod["source"].str.replace("MAIL","Mail")
citi_df_mod["source"] = citi_df_mod["source"].str.replace("WALK","Walk-in")

# 5) Rename values in status column
citi_df_mod["status"] = citi_df_mod["status"].str.replace("OPEN","Open")
citi_df_mod["status"] = citi_df_mod["status"].str.replace("RESOL","Resolved")
citi_df_mod["status"] = citi_df_mod["status"].str.replace("DUP","Duplicate")
citi_df_mod["status"] = citi_df_mod["status"].str.replace("ASSIG","Assigned")
citi_df_mod["status"] = citi_df_mod["status"].str.replace("CANC","Cancelled")
citi_df_mod["status"] = citi_df_mod["status"].str.replace("FAIL","Failed")
citi_df_mod["status"] = citi_df_mod["status"].str.replace("HOLD","On Hold")
#â€‹
# 6) Rename values in department column
citi_df_mod["department"]  = citi_df_mod["department"].str.replace("IT","Information Technology")
citi_df_mod["department"] = citi_df_mod["department"].str.replace("KCPD","Police")
citi_df_mod["department"] = citi_df_mod["department"].str.replace("Parks & Recreation","Parks & Rec")
citi_df_mod["department"] = citi_df_mod["department"].str.replace("Parks & Rec","Parks & Recreation")
citi_df_mod["department"] = citi_df_mod["department"].str.replace("Parks and Rec","Parks & Recreation")

citi_df_mod.head()

,source,department,category,type,detail,creation_year,creation_date,creation_time,status,days_to_close,street_address,council_district,lat,lon
0,Phone,NHS,Trash / Recycling,Trash Collection,Missed by City,2019,12/18/2019,01:52 PM,Resolved,6,2822 E 9th St,3,39.102651,-94.546809
1,Online,City Managers Office,Streets / Roadways / Alleys,Snow / Ice,Snow Route Verification,2020,01/12/2020,03:37 PM,Resolved,5,5635 N Manchester Ave,1,39.196584,-94.487959
2,Phone,Public Works,Signs,Traffic Sign,New Sign Request,2019,11/15/2019,03:01 PM,Resolved,3,301 W 45th St,4,39.045500,-94.590528
3,Phone,Water Services,Storm Water / Sewer,Storm Water Referral,Repair,2019,11/16/2019,01:16 PM,Resolved,26,1001 W 55th St,4,39.027698,-94.599931
4,Online,Water Services,Water,Leak,In Street,2019,11/27/2019,04:01 PM,Resolved,7,5200 Cherry St,4,39.031266,-94.581718

In [4]:
# Setup connection to mongodb
conn = "mongodb://localhost:27017"
client = pymongo.MongoClient(conn)
#â€‹
# Select database and collection to use
client.drop_database('citi_data')
db = client.citi_data
calls = db.calls
#â€‹
#â€‹
data = citi_df_mod.to_dict(orient='records')  # Here's our added param..
#â€‹
calls.insert_many(data)

In [13]:
array = []
for i in range(50):
    m = citi_df_mod['creation_date'][i].split("/")[0]
    d = citi_df_mod['creation_date'][i].split("/")[1]
    m_d = str(m) + "/" + str(d)
    array.append(m_d)
array

['12/18',
 '01/12',
 '11/15',
 '11/16',
 '11/27',
 '12/19',
 '11/16',
 '12/18',
 '11/15',
 '11/16',
 '11/16',
 '11/16',
 '12/19',
 '10/29',
 '11/06',
 '09/20',
 '11/16',
 '05/11',
 '11/16',
 '10/14',
 '11/06',
 '11/16',
 '12/20',
 '12/20',
 '12/20',
 '03/24',
 '11/17',
 '12/22',
 '07/03',
 '07/03',
 '11/16',
 '07/01',
 '12/22',
 '10/31',
 '10/31',
 '07/15',
 '10/19',
 '12/23',
 '11/17',
 '10/19',
 '11/17',
 '10/19',
 '12/23',
 '12/04',
 '03/25',
 '10/15',
 '12/09',
 '12/23',
 '12/31',
 '12/10']

In [38]:
citi_df_mod.loc[citi_df_mod['creation_date']=="unknown"]

Empty DataFrame
Columns: [source, department, category, type, detail, creation_year, creation_date, creation_time, status, days_to_close, street_address, council_district, lat, lon]
Index: []

In [24]:
i = 0

for i in range(len(citi_df_mod['creation_date'])):
    citi_df_mod['creation_date'][i]

KeyError: 50

In [14]:
#Parse the Day & Month from the Date
listy = []
#Loop through the 'CREATION DATE' data
for i in range(len(citi_df_mod['creation_date'])):
    #Use Split Function to Pull Out the Month & Day Values for Each Record
    months = citi_df_mod['creation_date'][i].split("/")[0]
    days = citi_df_mod['creation_date'][i].split("/")[1]
    #Concatenate the Values
    month_days = str(months) + "/" + str(days)
    #Append Month/Day Value to List
    listy.append(month_days)
#Create a New Series to Unpack the Month/Day Values
citi_df_mod['creation_month-day'] = pd.Series(listy)

KeyError: 50

In [22]:
#Reformat the 'CREATION DATE' Column
listy1 = []
#Loop through the 'CREATION DATE' data
for i in range(len(citi_df_mod['creation_date'])):
    #Use Split Function to Pull Out the Month & Day Values for Each Record
    months1 = citi_df_mod['creation_date'][i].split("/")[0]
    days1 = citi_df_mod['creation_date'][i].split("/")[1]
    years1 = citi_df_mod['creation_date'][i].split("/")[2]
    #Concatenate the Values
    years_month_days = str(years1) + "/" + str(months1) + "/" + str(days1)
    #Append Month/Day Value to List
    listy1.append(years_month_days)
#Create a New Series to Unpack the Year/Month/Day Values
citi_df_mod['creation_year-month-day'] = pd.Series(listy1)

KeyError: 50